[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr = '0xbcbb8d1cc06f54da4d447a9b536f3bd808f8ddd6589d249a5a012df75f8000fd'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
